Создание переменных
Gimasteev/KotlinSprintGimasteev pull request #1
Opened 2024-07-10 11:53 UTC by Gimasteev

1) Инициировал переменную для количества заказов
2) Текст с благодарностью за покупку

2024-07-10 13:35 UTC, Gimasteev commented
Не создавался в боте запрос на ссылку, поэтому сделал 2 задачи в одном пуше.

2024-07-11 06:54 UTC, ievetrovdev requested changes

2024-07-11 06:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +fun main(){
Привет! Хорошее оформление пулл реквеста, но есть несколько замечаний:
- по умолчанию все переменные делаем неизменяемыми, то есть val. и в условии сказано что количество интернет заказов 75
- комментарии, не относящиеся к решению или не несущие никакой полезной нагрузки для будущего себя или других разработчиков в команде – лучше не оставлять в продакшн коде
- переменные в Котлин принято называть в camelCase, без нижних подчеркиваний

2024-07-11 06:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task2.kt
> +fun main(){
Не забывай прожимать автоформатирование перед коммитом. по коду в паре мест не хватает пробелов

2024-07-11 06:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task2.kt
> +    val purchase_thankYou_text = "Спасибо за покупку, хорошего дня!"
В этом задании нужно также учесть все замечания из прошлого задания

2024-07-12 05:10 UTC, ievetrovdev approved these changes

2024-07-12 05:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    val orderQuantity: Int = 75
Теперь все отлично)

2024-07-12 06:53 UTC, merged