Урок 1 Задача 5 со звездочкой:)
Gimasteev/KotlinSprintGimasteev pull request #4
Opened 2024-07-10 13:31 UTC by Gimasteev

1) Получил часы
2) Получил минуты
3) Получил секунды
4) Распечатал

2024-07-11 06:58 UTC, ievetrovdev requested changes

2024-07-11 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val minutes = (seconds % 3600) / 60
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-07-11 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val last_seconds = (seconds % 60) % 60
Нижние подчеркивания в именах переменных не используются в котлине

2024-07-11 08:24 UTC, Gimasteev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val minutes = (seconds % 3600) / 60
Исправил, спасибо. // Разобрался как отвечать на комментарии))

2024-07-12 05:14 UTC, ievetrovdev requested changes

2024-07-12 05:14 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +const val SECONDS_IN_SPACE = 6480
Все отлично, только в константы нужно выносить числа, которые не могут измениться во время работы программы. Количество часов Гагарина в космосе может быть заменено на любое другое и программа должна также корректно отрабатывать. Мы подразумеваем что это число приходит на вход функции, также в условии сказано что это число должно быть переменной) Поэтому давай его вернем в main

2024-07-12 05:15 UTC, ievetrovdev requested changes

2024-07-12 05:15 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    println("$hours:$minutes:$lastSeconds")
Также попробуй для вывода использовать функцию `String.format`, она позволяет корректно выводить 0 в начале

2024-07-13 09:13 UTC, ievetrovdev approved these changes

2024-07-13 16:33 UTC, merged