Lesson2_task3_finish
Gimasteev/KotlinSprintGimasteev pull request #7
Opened 2024-07-11 03:44 UTC by Gimasteev

2024-07-12 14:21 UTC, ievetrovdev requested changes

2024-07-12 14:21 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +const val TIME_TRAVELLING = 457
Нельзя менять входные данные потому что так хочется, в работе надо работать с теми данными что дадут. Так что используем то что есть и все нужные вычесления проводим сами.
И опять не правильно разделены на константы. В данном случае только 60

2024-07-14 05:54 UTC, ievetrovdev requested changes

2024-07-14 05:54 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    timeStartMinutes = timeStartHours * MINUTES_IN_HOUR + 39
тут у тебя косяк, даже ИДЕ обращает внимание. Зачем объявлять переменную которую тут же перезаписываешь. К тому же писать 39 здесь это значит обесценить ве ранее обявленные переменные. В данном случае 39 нужно заменить на ранее объявленую переменную timeStartMinutes

2024-07-14 06:17 UTC, Gimasteev commented on src/main/kotlin/lesson2/lesson2_task3.kt
> +    timeStartMinutes = timeStartHours * MINUTES_IN_HOUR + 39
Да, заметил что ИДЕ ругается на объявленную переменную. Объявив 39, я тем самым хотел сообщить о старовых данных = 39 минутам, а затем преобразовать все в минуты. В таком слуае тобы не потерять нить смысла откуда я взял 39 минут, я оставлю данную переменную и перепишу код, который получает время прибытия. Да, станет длиннее, но суть не потеряется.

2024-07-14 14:23 UTC, ievetrovdev approved these changes
Да, теперь отлично

2024-07-15 03:15 UTC, merged